import type { Metadata } from "next";
import { Red_Rose } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { AlertProvider } from "./components/dashboard-admin/AlertContext";

const redRose = Red_Rose({
  subsets: ["latin"],
  variable: "--font-redrose",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={redRose.variable}>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AlertProvider>
          {children}
        </AlertProvider>
      </body>
    </html>
  );
}